### ISSUE TITLE
Mutating dataclass instances breaks optimized trie implementations

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/execution-specs#272]
The naive implementation rebuilds the entire trie to calculate the root, but any optimized implementation needs to mark leaves as dirty. Mutating objects in place complicates this process.

One possible solution is to freeze the dataclass objects.

**Comment by SamWilsn** [comment]
@ultratwo is looking at this.

**Comment by ultratwo** [comment]
I've done the easy part of this in pull request #275. The hard part is what to do about account storage. Storage is a trie (which is mutable) that is currently stored in the immutable `Account` class.

The two possible solutions are:
1. Turn `storage` into `storage_root`, store the storage trie somewhere else and require updates the storage trie to update `storage_root` in `Account`.
2. Remove the `storage` from `Account` entirely and require callers to `encode_account()` to provide the `storage_root`.

I'm mildly in favour of approach 2. Mostly because the verkle trie proposal will move (most of) account storage out of the `Account` object and into the main trie, so code shouldn't rely on `storage` being in `Account` for future proofing. Also being forced to recalculate the storage root every time storage changes seems annoying and inefficient.

**Comment by voith** [comment]
@ultratwo @SamWilsn Can we close this?

**Comment by ultratwo** [comment]
Yes, this was fixed ages ago.
