### ISSUE TITLE
EIP-161: State trie clearing (invariant-preserving alternative)

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/execution-specs#357]
https://eips.ethereum.org/EIPS/eip-161

**Comment by ultratwo** [comment]
I am probably the best placed person to do this.

**Comment by ultratwo** [comment]
The way this change is specified in the EIP is quite complicated, so I propose to implement this in a different (but equivalent) way.

a. `CREATE` increments the nonce before calling initcode (same as EIP).
b. The distinction between `None` (not present) and `EMPTY_ACCOUNT` in the State is abolished for all purposes except state root calculation.
c. When an account is set to `EMPTY_ACCOUNT`/`None` in the trie it will be represented as `None` (i.e. the key will be deleted)
d. When an operation would send `0` Ether to an account it must check if account is represented in the trie as `EMPTY_ACCOUNT` and replace it by `None` if so.

The EIP explicitly specifies that the replacement in d only happens at the end of the transaction, but this doesn't matter because of b.
