### ISSUE TITLE
Change repository name to "Execution Layer Specification"

### ISSUE THREAD

**Issue by uink45** [ethereum/execution-specs#440]
This issue proposes a change for the repository's name to Execution Layer Specification.

**Comment by Spore-Druid-Bray** [comment]
This allows the acronym "EELS" to be used, which is pleasing.

**Comment by timbeiko** [comment]
I'd push back a bit against including "Ethereum" in the name of the repo, because that's already the name of the GH org, see:
<img width="364" alt="Screen Shot 2022-01-27 at 6 11 41 AM" src="https://user-images.githubusercontent.com/9390255/151375630-18192f94-68a6-4fde-800d-38deaac20f1b.png">

Slight preference for brevity, but not a hill I will die on. I think the https://github.com/ethereum/consensus-specs repo should have the same format, though, so if we change things here, we should also change them there.

**Comment by uink45** [comment]
Hey @timbeiko, thanks for the feedback! I will apply the changes you suggested.

**Comment by SamWilsn** [comment]
An eel somehow made it into the GitPOAP for this repository 😇

![gitpoap-2021-ethereum-execution-client-specifications-contributor-2021-logo-1656529094347](https://user-images.githubusercontent.com/57262657/179580636-d9af6a22-b2f4-4e06-88ae-1a56cc23d4e7.png)
