### ISSUE TITLE
follow up on berlin spec

### ISSUE THREAD

**Issue by chaals** [ethereum/execution-specs#50]
Is the Berlin upgrade spec document in this repo the official one? It is really hard to tell - and the fact that it is still a work in progress from before the deployment date suggests it isn't, but other stuff I find pointing to this repo (e.g. cat herders' blog, but with broken URL from before a re-org) suggests it is.

Either way, it would be good to clarify (and maybe clean up after deployment).

@timbeiko are you the right person to annoy for this?

**Comment by timbeiko** [comment]
@chaals the [berlin.md file](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/mainnet-upgrades/berlin.md) in this repo lists the various EIPs that have been included in Berlin. Nothing has changed there since Berlin went live. Unfortunately, we don't (yet) maintain a full spec in this repository yet. The [Yellowpaper repo](https://github.com/ethereum/yellowpaper/commits/master) seems still at Istanbul. It seems like the [KEVM project](https://github.com/kframework/evm-semantics/tree/berlin-hardfork) is more up to date. 

With the upcoming merge between Eth1 & Eth2, my focus is on trying to get a python-style spec for Eth1 which could match what is currently in the [eth2.0-specs repository](https://github.com/ethereum/eth2.0-specs/). Post-merge, you can expect that repository to (eventually) contain the entire Ethereum spec.
