### ISSUE TITLE
Investigate pytest memory usage

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/execution-specs#516]
The memory usage of the hardfork tests (yes, even excluding ethash) has been increasing, and limited parallelization. We should investigate why the tests use so much memory, and come up with some potential solutions to fix it.

**Comment by gurukamath** [comment]
@SamWilsn @petertdavies I investigated this issue. 

Some tests in the following family of tests use ~3.6 GB of memory

`stStaticCall/static_Return50000` (multiple tests)
`stQuadraticComplexityTest/Return50000` (multiple tests)
`stStaticCall/static_Call50000` (multiple tests)
`stTimeConsuming/static_Call50000` (multiple tests)

I guess the root cause for such high memory consumption is the fact `child_evm` creating opcodes like `staticcall` are recursively called 50000 times in these tests. Since we do not clean up the child_evm's until the very end of a these, these children start piling up in memory.

One solution would be to optimise the `collect_touched_accounts` function which uses these child evm's at the end. But we might end up with some very "non-spec-like" code.

An alternative (much simpler) solution would be to make Github Actions run on a single thread. Since accuracy is more important on CI than speed, I believe this is a valid trade-off. We can still run tests in parallel while running locally.

Altough some of these "high memory" tests existed in Byzantium and Constantinople, many more have been added in Istanbul making it more likely that the workers crash after Istanbul. It might also start getting worse as we move towards `Berlin` and `London`

**Comment by SamWilsn** [comment]
Damn, that's fun.

How much complexity would we add if we created a `bigmem` pytest marker, and run `-m "not bigmem" -n auto` followed by a `-m bigmem -n 0`?

**Comment by gurukamath** [comment]
I think this is doable since it does not add any complexity to the specs source code itself.

The only thing I am unsure of is how the code coverage estimation is affected if we run multiple `pytest` commands. Would we get a combined report? Would you have any insights here? 

Perhaps, this aspect of `codecov` is customizable. I'll look into it.

**Comment by SamWilsn** [comment]
I think it'd add some complexity to the `tests/` directory, but it might be minimal.
